"""empty message

Revision ID: 4fd2387882b8
Revises: 3cdb89db7e50
Create Date: 2024-05-13 11:34:20.412576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd2387882b8'
down_revision = '3cdb89db7e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandwiches_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sandwiches_table', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
